export const experienceLevels = [
    { value: 'Entry-level', label: 'Entry-level' },
    { value: 'Mid-level', label: 'Mid-level' },
    { value: 'Senior', label: 'Senior' },
    { value: 'Not Specified', label: 'Not Specified' },
]

export const developerSkills = [
    { value: "javascript", label: "JavaScript" },
    { value: "python", label: "Python" },
    { value: "java", label: "Java" },
    { value: "csharp", label: "C#" },
    { value: "ruby", label: "Ruby" },
    { value: "php", label: "PHP" },
    { value: "html", label: "HTML" },
    { value: "css", label: "CSS" },
    { value: "sass", label: "Sass" },
    { value: "less", label: "Less" },
    { value: "bootstrap", label: "Bootstrap" },
    { value: "tailwind", label: "Tailwind CSS" },
    { value: "react", label: "React" },
    { value: "angular", label: "Angular" },
    { value: "vue", label: "Vue.js" },
    { value: "nextjs", label: "Next.js" },
    { value: "nuxtjs", label: "Nuxt.js" },
    { value: "nodejs", label: "Node.js" },
    { value: "express", label: "Express" },
    { value: "django", label: "Django" },
    { value: "flask", label: "Flask" },
    { value: "rails", label: "Ruby on Rails" },
    { value: "postgresql", label: "PostgreSQL" },
    { value: "mysql", label: "MySQL" },
    { value: "mongodb", label: "MongoDB" },
    { value: "redis", label: "Redis" },
    { value: "aws", label: "AWS" },
    { value: "azure", label: "Microsoft Azure" },
    { value: "gcp", label: "Google Cloud Platform" },
    { value: "docker", label: "Docker" },
    { value: "kubernetes", label: "Kubernetes" },
    { value: "git", label: "Git" },
    { value: "jenkins", label: "Jenkins" },
    { value: "agile", label: "Agile Methodology" },
    { value: "scrum", label: "Scrum" },
    { value: "sql", label: "SQL" },
    { value: "nosql", label: "NoSQL" },
    { value: "restapi", label: "RESTful APIs" },
    { value: "graphql", label: "GraphQL" },
    { value: "typescript", label: "TypeScript" },
    { value: "flutter", label: "Flutter" },
    { value: "react-native", label: "React Native" },
    { value: "swift", label: "Swift" },
    { value: "kotlin", label: "Kotlin" },
    { value: "go", label: "Go" },
    { value: "rust", label: "Rust" },
    { value: "scala", label: "Scala" },
    { value: "tensorflow", label: "TensorFlow" },
    { value: "pytorch", label: "PyTorch" },
    { value: "machine-learning", label: "Machine Learning" },
    { value: "data-science", label: "Data Science" },
    { value: "big-data", label: "Big Data" },
    { value: "devops", label: "DevOps" },
    { value: "cybersecurity", label: "Cybersecurity" },
    { value: "ui-ux", label: "UI/UX Design" },
    { value: "testing", label: "Software Testing" },
    { value: "project-management", label: "Project Management" },
    { value: "linux", label: "Linux" },
    { value: "windows", label: "Windows" },
    { value: "macos", label: "macOS" },
    { value: "figma", label: "Figma" },
    { value: "sketch", label: "Sketch" },
    { value: "photoshop", label: "Adobe Photoshop" },
    { value: "illustrator", label: "Adobe Illustrator" },
    { value: "xd", label: "Adobe XD" },
    { value: "pandas", label: "Pandas" },
    { value: "numpy", label: "NumPy" },
    { value: "matplotlib", label: "Matplotlib" },
    { value: "selenium", label: "Selenium" },
    { value: "cypress", label: "Cypress" },
    { value: "jest", label: "Jest" },
    { value: "enzyme", label: "Enzyme" },
    { value: "react-testing-library", label: "React Testing Library" },
    { value: "gitlab", label: "GitLab" },
    { value: "github", label: "GitHub" },
    { value: "bitbucket", label: "Bitbucket" },
    { value: "aws-lambda", label: "AWS Lambda" },
    { value: "aws-s3", label: "AWS S3" },
    { value: "aws-ec2", label: "AWS EC2" },
    { value: "aws-rds", label: "AWS RDS" },
    { value: "aws-ecs", label: "AWS ECS" },
    { value: "aws-eks", label: "AWS EKS" }
];